bug: bug.cpp
	clang++ -std=c++20 -Wall -Wextra -save-temps bug.cpp -o bug

usecase: usecase.cpp
	clang++ -std=c++20 -Wall -Wextra -save-temps usecase.cpp -o usecase

workaround: workaround.cpp
	g++ -std=c++20 -Wall -Wextra -save-temps workaround.cpp -o workaround
