generic: generic.cpp
	g++ -std=c++20 -Wall -fconcepts-diagnostics-depth=3 generic.cpp -o generic 

bug: bug.cpp
	g++ -std=c++20 -Wall -fconcepts-diagnostics-depth=3 bug.cpp -o bug 

module: module.cpp speech.cpp
	g++ -std=c++20 -Wall -fmodules-ts speech.cpp module.cpp -o module

# bug: bug.cpp
# 	clang++ -std=c++20 -Wall bug.cpp -o bug 
